// flow-typed signature: 855844cc0130655d6aa3e4704a57e2a3
// flow-typed version: <<STUB>>/simplemark_v^0.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplemark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplemark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplemark/lib/charChecks' {
  declare module.exports: any;
}

declare module 'simplemark/lib/index' {
  declare module.exports: any;
}

declare module 'simplemark/lib/stackWork' {
  declare module.exports: any;
}

declare module 'simplemark/src/charChecks' {
  declare module.exports: any;
}

declare module 'simplemark/src/index' {
  declare module.exports: any;
}

declare module 'simplemark/src/stackWork' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplemark/lib/charChecks.js' {
  declare module.exports: $Exports<'simplemark/lib/charChecks'>;
}
declare module 'simplemark/lib/index.js' {
  declare module.exports: $Exports<'simplemark/lib/index'>;
}
declare module 'simplemark/lib/stackWork.js' {
  declare module.exports: $Exports<'simplemark/lib/stackWork'>;
}
declare module 'simplemark/src/charChecks.js' {
  declare module.exports: $Exports<'simplemark/src/charChecks'>;
}
declare module 'simplemark/src/index.js' {
  declare module.exports: $Exports<'simplemark/src/index'>;
}
declare module 'simplemark/src/stackWork.js' {
  declare module.exports: $Exports<'simplemark/src/stackWork'>;
}
